import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import { RootHeader } from '@/components/header/header'
import { RootFooter } from '@/components/footer/footer'

import { Switch } from '@components/switch'
import { Wraper } from '@components/Wraper'
import { getI18n, getScopedI18n, getCurrentLocale } from '@/locales/server';  
import { Provider } from './provider';

const inter = Open_Sans({ subsets: ['greek']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const lang = await getI18n()
  const locale = getCurrentLocale()
  return (
    <html lang="ru">
      <body className={`${inter.className} no-scrollbar`}>
        <Provider locale={locale}>
          <RootHeader className="header-layout fixed top-0"/>
            <Switch/>
            <Wraper>
              {children}
            </Wraper>
          <RootFooter className="footer-layout" />
        </Provider>
      </body>
    </html>
  )
}
