import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function InvestorsLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <div className="w-full bg-fixed bg-top bg-no-repeat bg-[url('../../public/investors/bk.webp')]">
      {children}
    </div>
  )
}
